micronaut:
    application:
        name: transfer

datasources:
    default:
        url: jdbc:h2:mem:devDb;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
        username: sa
        password: ''
        driverClassName: ${JDBC_DRIVER:org.h2.Driver}
jpa:
    default:
        packages-to-scan:
        - 'ru.mn.transfer'
        properties:
            hibernate:
                hbm2ddl:
                    auto: update
                show_sql: true

datasources.default: {}